### ISSUE TITLE
Still attempts to make a docstring when not in function & when already exists

### ISSUE THREAD

**Issue by Modelmat** [NilsJPWerner/autoDocstring#12]
It doesn't realise that this is not in a function:
![image](https://user-images.githubusercontent.com/25718989/34474156-1a8f76b4-efcf-11e7-8a14-f8ae27eb1a22.png)
And this one it doesn't realise it already has a docstring.
![image](https://user-images.githubusercontent.com/25718989/34474163-35ea355c-efcf-11e7-8a68-71e5b513151c.png)

**Comment by NilsJPWerner** [comment]
Hi Modelmat, this is working as currently intended. I am copying the behavior of the [docBlockr](https://github.com/adambullmer/sublime_docblockr_python) extension for sublime text where it creates a basic docstring if no function definition is found. 

This also true for the second screenshot. The extension checks whether the previous triple quotes are the closing quotes of an earlier docstring. In your case the earlier docstring is already closed so it allows the generation of a new one. I prefer to be permissive in this case since the activation is an explicit action by the user.

If this is undesired I could add a setting that disables this functionality.

**Comment by Modelmat** [comment]
This is the issue with the second one really: 
![image](https://user-images.githubusercontent.com/25718989/34500770-445bcc54-f060-11e7-8c1f-a19bc2bcb4ca.png)

**Comment by NilsJPWerner** [comment]
Ah I hadn't taken in to account people using the triple quotes for strings in functions. Thanks for catching that.

**Comment by NilsJPWerner** [comment]
Solved https://github.com/NilsJPWerner/autoDocstring/pull/42
