### ISSUE TITLE
Arguments in the doc string are not generating for all the functions

### ISSUE THREAD

**Issue by Ayan-Kumar-Saha** [NilsJPWerner/autoDocstring#148]
It is generating the argument section in the docstring for some of the functions but not for all functions, though all the functions have arguments. 

- autoDocstring Version: v0.5.3
- Operating System: Ubuntu 20.04 LTS
- Vscode Version: 1.46.1

**Expected Result:**
```python
def get_filename(file_path):

    """[summary]

    Args:
        file_path ([type]): [description]

    Returns:
        [type]: [description]
    """

    file_name = file_path.split('/')[-1]

    return file_name
```

**Actual Result:**
```python
def get_filename(file_path):

    """[summary]

    Returns:
        [type]: [description]
    """

    file_name = file_path.split('/')[-1]

    return file_name
```

**Comment by HaaLeo** [comment]
This is because there is a blank line between the function definition and where you start to generate the docstring. If you generate the docstring immediatly after the function definiton it works as expected.
```python
def foo(bar):
    # Generate on this line
    # Not on this line
    pass
```

Example gif:
![issue_docstring](https://user-images.githubusercontent.com/23164374/86099784-3c802000-bab8-11ea-94eb-5d847fbff5b0.gif)

**Comment by Ayan-Kumar-Saha** [comment]
Thanks, it works.
