### ISSUE TITLE
Unecessary trailling spaces

### ISSUE THREAD

**Issue by badouralix** [NilsJPWerner/autoDocstring#6]
`autoDocstring` adds trailling spaces on blank line 3 of the following example, and more generally on blank lines between sections.
```python
1  def function():
2     """[summary]
3     
4     [description]
5     """
6     pass
```
They should be removed in order to be compliant with [PEP8](http://pylint-messages.wikidot.com/messages:c0303).

**Comment by NilsJPWerner** [comment]
You are correct, I didn't notice it because I have set vscode to automatically remove trailing spaces. Will fix asap.

**Comment by badouralix** [comment]
I'm pretty sure this is an easy fix, that I could do myself and then submit an PR. Unfortunately, I couldn't properly set up VSCode to dev plugins... Even the [hello world example](https://code.visualstudio.com/docs/extensions/example-hello-world) build fails on my computer... ( `node v8.7.0`, `npm 5.5.1` and `vscode 1.18.1` ). How is your environment set up ?

**Comment by NilsJPWerner** [comment]
Hi, sorry for the deley. I took a look at this and the change will be a little more involved than I thought since the indentation is created by the insertSnippet vscode editor function which isn't intelligent enough to deal with trailing spaces: https://github.com/Microsoft/vscode/issues/20112 I will need to build my own indentation method when generating the snippet. 

As for the dev environment. I have `node v8.9.1`, `npm 5.5.1` and `vscode 1.19.0` with nothing else special. What is the failure message? It may be better to debug that issue at the official vscode repo.

**Comment by NilsJPWerner** [comment]
I have opened an [issue](https://github.com/Microsoft/vscode/issues/40613) on the vscode github page. I will revisit this when the issue is fixed. For now enabling the `files.trimTrailingWhitespace` or using the trailing-spaces extension should take care of the problem.
