### ISSUE TITLE
Wrong docstring for yield-only generator

### ISSUE THREAD

**Issue by zgoda** [NilsJPWerner/autoDocstring#91]
```python
def gen_object_keys(
            client, bucket: str, prefix: str
        ) -> Generator[Tuple[str, str], None, None]:
    """Generator to get S3 object identifiers (bucket + key) that lists
    matching objects in S3.

    :param client: Boto3 S3 client object
    :type client: Client
    :param bucket: S3 bucket name
    :type bucket: str
    :param prefix: object prefix for filtering
    :type prefix: str
    :return: [description]
    :rtype: Generator[Tuple[str, str], None, None]
    :yield: [description]
    :rtype: Generator[Tuple[str, str], None, None]
    """
    kw = {
        'Bucket': bucket,
        'Prefix': prefix,
    }
    while True:
        resp = client.list_objects_v2(**kw)
        for obj in resp['Contents']:
            key = obj['Key']
            data = client.head_object(Bucket=bucket, Key=key)
            if data['ContentType'] in WAVE_MIME_TYPES:
                yield bucket, key
        try:
            kw['ContinuationToken'] = resp['NextContinuationToken']
        except KeyError:
            break
```

As you see, this generator only yields, it does not return anything, yet still entry for return is generated (and is duplicate of yield entry).

**Comment by HaaLeo** [comment]
This is because the [`parseReturn()`](https://github.com/NilsJPWerner/autoDocstring/blob/master/src/parse/parse_parameters.ts#L78) function always checks the function definition to infer information regarding the return type. However, the `parseYields()` method always requires an actual `yield` statement to generate the `:yield:` entry in the docstring.

To fix this the `parseReturn()` function can be changed accordingly. However, technically this would introduce a _breaking change_ since currently the following docstring is generated for functions like this:
```python
def foo() -> int:
    """[summary]
    
    Returns:
        int -- [description]
    """
    pass
```
When changing the implementation similar to the `parseYields()` this would lead to:
```python
def foo():
    """[summary]
    """
    pass
```

@NilsJPWerner what is the desired behaviour for a fix you would accept in a PR?

**Comment by NilsJPWerner** [comment]
I like the current behavior where you can create a function's docstring based off the function signature before writing the rest of the function. However this bug does need to be fixed.

We could check the return type for yielding type hints like `Iterator` & `Generator` to create the appropriate docstring entry. There seems to only be a few applicable [type hints](https://docs.python.org/3/library/typing.html#typing.Generator) and they denote whether there is also a return value. That way both parseYields and parseReturns would only need to inspect the function signature and we don't make a breaking change.

What do you think @HaaLeo?

**Comment by HaaLeo** [comment]
@NilsJPWerner I like that idea. I think this should work 👍
